services:
  # distgit:
  #   build:
  #     context: docker/distgit/
  #   hostname: distgit
  #   stdin_open: true
  #   tty: true
  #   volumes:
  #     - .:/opt/copr:z
  #     - dist-git:/var/lib/dist-git:z

  distgit:
    build:
      context: docker/distgit/
    hostname: distgit-httpd
    stdin_open: true
    tty: true
    ports:
      - "5080:5080"
    volumes:
      - .:/opt/:z
      - dist-git:/var/lib/dist-git:z
    # command: /usr/sbin/httpd -DFOREGROUND
    command: bash

  forgejo:
    image: codeberg.org/forgejo/forgejo:10
    hostname: forgejo
    ports:
      - "5081:3000"
      - "2222:22"
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - FORGEJO__server__ROOT_URL=http://localhost:5081/
    volumes:
      - forgejo-data:/data

volumes:
  dist-git:
  forgejo-data:
